name: 'GitHub repository operation'
description: 'Github Action to interact with the github repository'
author: 'jikuma'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  operation:
    description: "Define an operation you want to take, e.g 'create a release', 'upload to release'"
    default: 'create a release'
    required: true
  tag_name:
    description: 'tag name of the release'
    default: '${GITHUB_SHA}'
  release_title:
    description: 'title of the release'
  release_note:
    description: 'add a release note'
  release_draft:
     description: 'is this a draft release'
  release_prerelease:
     description: 'is this a pre-release version'
  asset_filepath:
     description: 'filepath for the asset to be uploaded to release'

runs:
  using: 'node12'
  main: 'lib/main.js'
